language: php

php: [5.4, 5.5, 5.6, hhvm]

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
    - vendor

services:
  - mongodb

before_script:
  - echo 'extension = mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev

script: ./vendor/bin/phpspec run

